### ISSUE TITLE
unsupported operand type(s) for -: 'float' and 'decimal.Decimal'

### ISSUE THREAD

**Issue by NL647** [bancorprotocol/fastlane-bot#180]
Hello, since last update i get this error in "multi" mode

`2023-10-26 22:49:10,659 [fastlane:ERROR] - [bot:run:single] unsupported operand type(s) for -: 'float' and 'decimal.Decimal'
2023-10-26 22:49:10,659 [fastlane:ERROR] - Error in main loop: unsupported operand type(s) for -: 'float' and 'decimal.Decimal'`

and also there's an error in "bancor_v3" mode :
`2023-10-26 20:48:07,830 [fastlane:ERROR] - Error in main loop: {'code': -32000, 'message': 'filter not found'}`

Any idea how to fix these errors?

Thanks in advance for your help.

**Comment by mikewcasale** [comment]
> Hello, since last update i get this error in "multi" mode
> 
> `2023-10-26 22:49:10,659 [fastlane:ERROR] - [bot:run:single] unsupported operand type(s) for -: 'float' and 'decimal.Decimal' 2023-10-26 22:49:10,659 [fastlane:ERROR] - Error in main loop: unsupported operand type(s) for -: 'float' and 'decimal.Decimal'`
> 
> and also there's an error in "bancor_v3" mode : `2023-10-26 20:48:07,830 [fastlane:ERROR] - Error in main loop: {'code': -32000, 'message': 'filter not found'}`
> 
> Any idea how to fix these errors?
> 
> Thanks in advance for your help.

Can you provide your run configurations? Running the default `python main.py` I do not get any errors.

**Comment by NL647** [comment]
Hello, 
I was also using : `python main.py` .
I re-installed my virtual env and it  works now.
Thank's.
