### ISSUE TITLE
Can anyone provide the instructions to use a private eth node? Already have the node

### ISSUE THREAD

**Issue by mazgalesc** [bancorprotocol/fastlane-bot#246]
As tittle says i am trying to setup the bot to work with a private node but I encounter some issues. Can anyone provide what to change?

**Comment by Lesigh-3100** [comment]
In fastlane_bot/config/provider.py in the class _ConfigProviderAlchemy, you can change RPC_URL to the URL of your private node. 

For example the default local node would be set as:
self.RPC_URL = "http://localhost:8545"

Note that your node needs to be configured to accept Web3 & the correct port, and it needs to handle any firewall settings you may have. 

Closing this issue but feel free to reach out on the developer Telegram channel if you have any more questions:
https://t.me/BancorDevelopers
