### ISSUE TITLE
Production monitoring spreadsheet

### ISSUE THREAD

**Issue by mikewcasale** [bancorprotocol/fastlane-bot#275]
## Enhancement Description
- Create an automatically updated spreadsheet that indicates when the last known "successful" iteration of arb search completed, for each production job.

## Rationale
- Provide basic health status which can be easily referenced by non-devs.

## Impact Analysis
- Monitoring: Enhances monitoring.

**Comment by zavelevsky** [comment]
Interesting data:
- last life signal from the bot
- last time each exchange was used in a route
- which strategies / route we looked into

This is to provide quick way for someone to know that the bot is running and that what they thing is an arb really isn't - as the bot looked into it
