### ISSUE TITLE
hex string without 0x prefix

### ISSUE THREAD

**Issue by mikewcasale** [bancorprotocol/fastlane-bot#306]
## Bug Description
- A float block number gets introduced to the pool data during processing, which eventually leads to an `hex string without 0x prefix` error. Need to find the root cause (where the float value is first introduced) and correct - this most likely occurs within the async processes. Then there should be validation of the block number types prior to calling for web3 events.
![2024-01-15 14 59 32](https://github.com/bancorprotocol/fastlane-bot/assets/46603283/079ccd9e-4c88-40ca-8637-e194cdc3a4fd)

## Severity Medium
- It is problematic but happens infrequently.

## Steps to Reproduce
- Can be reproduced with any v3.x version, but no direct steps to exactly reproduce. If you manually introduce a decimal/float value for a block number in the pool data, you can force the error to occur. 

## Expected Behavior
- The `hex string without 0x prefix` error should never occur, and the block number should always be stored and processed as integers. 

## Actual Behavior
- The block number is stored and processed as a float type, with causes a `hex string without 0x prefix` error to occur when calling web3 to fetch events happening between block A and B.

## Impact Analysis (to be filled by contributors)
- Automated Tests: We should add tests to ensure type checks for block numbers in the pool data.

**Comment by joshmuente** [comment]
I also get that error. Bot then tries to continue and runs in the error again instantly. So basically an error loop spamming the logs. Restarting the bot manually seems to fix the issue for some time

**Comment by barakman** [comment]
Can you please share the related log?

**Comment by joshmuente** [comment]
> Can you please share the related log?

before I restarted the bot I updated from v3.0.16 to v3.0.17.
Until now the error did not appear!

**Comment by joshmuente** [comment]
I got the error today.
-  `Could not transact with/call contract function, is contract deployed correctly and chain synced?` like 20 times.
-  `execution aborted (timeout = 5s)` once.
- Then `Exception: TypeError int() argument must be a string, a bytes-like object or a number, not 'NoneType'`
- Then `invalid argument 0: hex string without 0x prefix` loop forever.
[bot-logs.txt](https://github.com/bancorprotocol/fastlane-bot/files/13993592/bot-logs.txt)

**Comment by barakman** [comment]
Intermediate conclusion:
For some `block` in `mgr.pool_data`, the value of `block["last_updated_block"]` is not integer (probably float).

**Comment by barakman** [comment]
> I got the error today.
> 
> * `Could not transact with/call contract function, is contract deployed correctly and chain synced?` like 20 times.
> * `execution aborted (timeout = 5s)` once.
> * Then `Exception: TypeError int() argument must be a string, a bytes-like object or a number, not 'NoneType'`
> * Then `invalid argument 0: hex string without 0x prefix` loop forever.
>   [bot-logs.txt](https://github.com/bancorprotocol/fastlane-bot/files/13993592/bot-logs.txt)

@joshmuente:

Can you please update your bot's version to the latest release, and report back with the log file as soon as you run into this error again?

Thank you :)

**Comment by barakman** [comment]
Solution attempt implemented in PR #320

**Comment by joshmuente** [comment]
> > I got the error today.
> > 
> > * `Could not transact with/call contract function, is contract deployed correctly and chain synced?` like 20 times.
> > * `execution aborted (timeout = 5s)` once.
> > * Then `Exception: TypeError int() argument must be a string, a bytes-like object or a number, not 'NoneType'`
> > * Then `invalid argument 0: hex string without 0x prefix` loop forever.
> >   [bot-logs.txt](https://github.com/bancorprotocol/fastlane-bot/files/13993592/bot-logs.txt)
> 
> @joshmuente:
> 
> Can you please update your bot's version to the latest release, and report back with the log file as soon as you run into this error again?
> 
> Thank you :)

log file is really huge.. here are the first 1000 lines.
[new-logs.txt](https://github.com/bancorprotocol/fastlane-bot/files/14030482/new-logs.txt)
