### ISSUE TITLE
Add Handling of Flashloan Fee

### ISSUE THREAD

**Issue by Lesigh-3100** [bancorprotocol/fastlane-bot#346]
## Enhancement Description
This feature will add support for flashloans from sources that take a fee. 

The implementation will be to add a flashloan fee constant per blockchain in network.py, and use it to calculate the expected profit after flashloan fee.

## Rationale
- Why is this enhancement important?
This is important to support blockchains in which there is no viable free flashloan source. 

## Impact Analysis
- Automated Tests: Implications on testing (new/changed)
Add Test to check that the fee is working for each chain. Add unit test for the calculation. 

- Risks: What are the risks associated with this enhancement?
No obvious risks. 

- Performance: Expected performance impacts and how to measure them
No expected performance impact.
- Monitoring: Changes required in the monitoring system
Nothing
- Logging: Do we need additional logs?
Optional log stating expected flashloan fee
- Documentation: Updates or new documentation needed?
No

**Comment by ashachaf** [comment]
consider a case in which you have more than 1 source of flashloan and each source and token might have a different fee level
