### ISSUE TITLE
Problems in txhelpers with TX Submission & L1 gas fee calculation

### ISSUE THREAD

**Issue by Lesigh-3100** [bancorprotocol/fastlane-bot#351]
## Bug Description
Issue 1:
Signed transactions are now submitted to the functions submit_private_transaction, submit_transaction, and cancel_private_transaction. This currently works for submit_private_transaction, however it is not correctly handled in submit_transaction & cancel_private_transaction.

Issue 2:
In the function _get_layer_one_gas_fee, contract calls as implemented fail & must be wrapped in async functions. 

## Severity (High/Medium/Low)
High

## Steps to Reproduce
Run the Bot on Base. The bot fails when it tries to calculate the L1 gas fee, and when it tries to submit a transaction. 

## Expected Behavior
L1 gas fee should be calculated, and transactions should be submitted properly. 

## Actual Behavior
L1 gas fee API calls fail, and transactions fail to be submitted.

## Impact Analysis (to be filled by contributors)
- Automated Tests: Are there existing tests covering this? Do we need new tests?
No tests currently cover these. A test that covers the 

- Risks: Potential areas affected by this bug and its probable fix
Any place that submits transactions should be thoroughly checked. This includes the files:
- pool_shutdown
- txhelpers

Affected functions:
- submit_transaction
- submit_private_transaction 
- cancel_private_transaction

- Performance: Is this bug affecting performance?
No
- Monitoring: Does this affect any current monitoring? Any new alerts needed?
No
- Logging: Any changes required in logging?
No
- Documentation: Updates needed in documentation?
No

**Comment by barakman** [comment]
Split into issues #352 and #353
