### ISSUE TITLE
Test files under NBTest

### ISSUE THREAD

**Issue by sklbancor** [bancorprotocol/fastlane-bot#448]
Those two files are in the NBTest folder

https://github.com/bancorprotocol/fastlane-bot/blob/develop/resources/NBTest/NBTest_070_TestCarbonTradeSplitter.py

https://github.com/bancorprotocol/fastlane-bot/blob/develop/resources/NBTest/NBTest_071_TestWrapUnwrapProcessor.py

Those are valid test files and therefore most likely not NBTest source files, therefore they have no business being there. They need to be renamed and moved to fastlane_bot/tests

**Comment by barakman** [comment]
Resolved in PR #444
