### ISSUE TITLE
Can get rid of the if '-' in cid

### ISSUE THREAD

**Issue by mikewcasale** [bancorprotocol/fastlane-bot#466]
Can get rid of the `if '-' in cid` above, and just do `cid=cid.split('-')[0]` here.

_Originally posted by @barakman in https://github.com/bancorprotocol/fastlane-bot/pull/449#discussion_r1531983141_

**Comment by barakman** [comment]
This appears to no longer be in the code (and it's a minor cleanup regardless); closing
