### ISSUE TITLE
Cleopatra and Stratum exchanges not handled correctly

### ISSUE THREAD

**Issue by barakman** [bancorprotocol/fastlane-bot#488]
## Bug Description

Cleopatra and Stratum exchanges not handled correctly

## Severity (High/Medium/Low)

High

## Details

Currently, for every Solidly-like pool contract, the bot retrieves the corresponding factory contract by calling a function in the pool contract.

In the case of Velocimeter pool contracts, that function is named `voter`; in all other cases, it is named `factory`.

The handling of Cleopatra exchanges, which is currently broken for two different reasons:
1. The bot attempts to retrieve the factory contract by calling non-implemented function `factory` in the pool contract
2. The bot assumes that the pool contract uses decimals=4, while this contract actually uses decimals=18

The handling of Stratum exchanges, which is currently broken for two different reasons:
1. The bot attempts to retrieve the factory contract by calling non-implemented function `voter` in the pool contract
2. The bot assumes that the pool contract uses decimals=4, while this contract actually uses decimals=18

In order to fix the handling of Cleopatra exchanges:
1. The bot should retrieve the factory contract by reading storage-slot 11 in the pool contract
2. The bot should assume that the pool contract uses decimals=18

Fixing the handling of Stratum exchanges is less trivial, primarily because the factory contract cannot be retrieved from the storage of the pool contract (neither by calling a function on that contract, nor by reading this value directly from the contract storage).

That address can probably be retrieved by fetching the first event on the pool contract, because the factory contract is the creator of the pool contract (i.e., the value of `msg.sender` in the constructor of the pool contract was the address of the factory contract).

Another option is to use the hard-coded value `0x061FFE84B0F9E1669A6bf24548E5390DBf1e03b2`, which is the address of a Stratum factory contract.

**Comment by Lesigh-3100** [comment]
1. Your solution to getting the Factory address for Cleopatra sounds good. 
2. For Stratum - hardcoding the address does not solve the problem this contract call was meant to address - which is to discover the exchange an unknown pool belongs to. 
3. The fee resolution in the code - "4" - is correct. If you disagree, please prove otherwise. 

I think a short-term solution of making the bot able to continue without receiving the factory address here would be a good solution.

**Comment by barakman** [comment]
> 1. Your solution to getting the Factory address for Cleopatra sounds good.
> 2. For Stratum - hardcoding the address does not solve the problem this contract call was meant to address - which is to discover the exchange an unknown pool belongs to.
> 3. The fee resolution in the code - "4" - is correct. If you disagree, please prove otherwise.
> 
> I think a short-term solution of making the bot able to continue without receiving the factory address here would be a good solution.

OK, my bad on the fee-resolution.
I was looking into the contract's `decimals` function, which of course has nothing to do with the fees.
That resolution appears to be hard-coded (either in the factory contract or in the pool contract or both).
So I'm gonna assume that you've carefully investigated that in order to determine that it is indeed 4 and not 18 for both of these exchanges (cleopatra ands stratum).

**Comment by barakman** [comment]
Have decided on removing the attempt to fetch factory addresses dynamically (during runtime).
