### ISSUE TITLE
`*args, **kwargs` -> `argsf1, argsf2` 

### ISSUE THREAD

**Issue by sklbancor** [bancorprotocol/fastlane-bot#493]
Once the RC is out of the way the `*args, **kwargs` should be converted to`argsf1, argsf2` as discussed on Telegram

_Originally posted by @sklbancor in https://github.com/bancorprotocol/fastlane-bot/pull/492#discussion_r1539024931_

**Comment by barakman** [comment]
This was indeed a horrible piece of code (in txhelpers.py), and it is handled (removed) as part of PR #529
