### ISSUE TITLE
Carbon strategies are duplicated from events

### ISSUE THREAD

**Issue by Lesigh-3100** [bancorprotocol/fastlane-bot#521]
## Bug Description
When a Strategy updated event occurs, the strategy is duplicated in the system due to having a different CID from the original strategy. This occurs due to using different inputs to generate the CID.

On startup: Bot called `add_pool_info` when processing pool data for Carbon Strategies. This resulted in creating a CID using exchange name, strat id, and fee:
```
f"{pool_info['exchange_name']} {pool_info['strategy_id']} {pool_info['fee']}
```

However, when updating from a Strategy Updated event, the bot called the `get_pool_cid` function to get a CID. This function used only exchange name & strat id to generate the CID.

```
args["exchange_name"] + " "+ str(args["strategy_id"]
``` 

This resulted in creating a new pool for the updated strategy, while retaining the original pool with now-stale data.

To fix this, the exact same inputs must be used to generate the CID - ideally only a single function should exist to generate the CID. 

## Severity (High/Medium/Low)
High

## Steps to Reproduce
Run bot with Carbon enabled & read_only=False. Wait for Carbon trade event. See Strategy duplicated with different CID. 

## Expected Behavior
Only a single instance of each Carbon strategy should exist in pool data.

## Actual Behavior
Up to two instances of each Carbon strategy can exist in pool data. 

## Impact Analysis (to be filled by contributors)
- Automated Tests: Are there existing tests covering this? Do we need new tests?
Will discuss.

- Risks: Potential areas affected by this bug and its probable fix
Low risk. Need to ensure only a single CID-generation function is called.
- Performance: Is this bug affecting performance?
No
- Monitoring: Does this affect any current monitoring? Any new alerts needed?
No
- Logging: Any changes required in logging?
No
- Documentation: Updates needed in documentation?
No

**Comment by barakman** [comment]
I'm seeing this in at least 3 places in the code:
1. Module `pools` / Class `PoolManager` / Function `pool_descr_from_info`
2. Module `pools` / Class `PoolManager` / Function `add_pool_info`
3. Module `utils` / Global Function `get_cid_base`

In addition to that, it appears as if somebody has implemented one way of constructing CIDs specifically for carbon v1 forks, and another way of constructing CIDs for all other cases.

This seems to be with some sort of specific intention, so just changing it without finding out the exact reason behind this is pretty risky and not necessarily a small straightforward change.

**Comment by Lesigh-3100** [comment]
> I'm seeing this in at least 3 places in the code:
> 
> 1. Module `pools` / Class `PoolManager` / Function `pool_descr_from_info`
> 2. Module `pools` / Class `PoolManager` / Function `add_pool_info`
> 3. Module `utils` / Global Function `get_cid_base`
> 
> In addition to that, it appears as if somebody has implemented one way of constructing CIDs specifically for carbon v1 forks, and another way of constructing CIDs for all other cases.
> 
> This seems to be with some sort of specific intention, so just changing it without finding out the exact reason behind this is pretty risky and not necessarily a small straightforward change.

The issue was that Carbon pool CIDs were constructed one way on startup, and a different way on Strategy Update. It's OK That it's constructed differently from other pool types, it just must be consistent.
