### ISSUE TITLE
Bot should only import from top level

### ISSUE THREAD

**Issue by sklbancor** [bancorprotocol/fastlane-bot#625]
_Originally posted by @sklbancor in https://github.com/bancorprotocol/fastlane-bot/pull/608#discussion_r1590957033_
         

The bot files should _only_ import from the top level in tools. This in particular relates to a number of the files in `modes` that import `T`. They should not be using it -- it is no longer part of the supported API (it is just a short for token ids; eg `T.WETH` is `WETH`). 

Note: it is still OK -- albeit not recommended -- to use higher level imports in tests.

**Comment by barakman** [comment]
Handled in PR #633
